name: Build and Deploy

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./hello

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: "5.0"

      - run: opam install . --deps-only --with-test

      - run: opam exec -- dune build @default

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'hello/_build/default/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
